### ISSUE TITLE
Gabriel Caruso

### ISSUE THREAD

**Issue by carusogabriel** [PHPSP/quero-palestrar#24]
Nome: **Gabriel Caruso**
E-mail: carusogabriel34@gmail.com
Cidade: *Itatiba - SP*
Facebook: [carusogabriel](https://www.facebook.com/carusogabriel)
Twitter: [carusogabriel](https://twitter.com/carusogabriel)
GitHub: [carusogabriel](https://github.com/carusogabriel)
LinkedIn: [carusogabriel](https://www.linkedin.com/in/carusogabriel)
SpeakerDeck e SlideShare: [carusogabriel](https://speakerdeck.com/carusogabriel)
Imagem: https://avatars3.githubusercontent.com/u/16328050?v=4
Biografia:

> Teve seu primeiro contato com a linguagem no ensino médio integrado ao ensino técnico, que o motivou a reescrever todo o site de sue antiga instituição de ensino.
A pouco conheceu o GitHub e descobriu o mundo open-source. Desde então, é o que tem feito para a comunidade: contribuindo e ajudando a programar um mundo melhor. Tem paixão em testes, principalmente na ferramente de automatização PHPUnit.
Recentemente tem trabalhado em ferramentas de automatização de refatoração de código legados com interpretatores PHP AST, escritos em PHP. Tem paixão por palestrar, ensinar, debater e problematizar diversos temas, desde Refatoração de Código a PSRs.

**Comment by marcelgsantos** [comment]
Oi @gabriel-caruso, tudo bem?

Ficou muito legal o cadastro das suas informações e sua biografia. Fiz apenas alguns ajustes pequenos para manter a consistência. :smiley: 

Vou te sugerir mais alguns ajustes nos seguintes pontos:

1. o trecho *"...tive meu 1º contato com a linguagem a 2 dois, no ensino médio..."* ficou meio confuso. Sugiro uma reescrita como *"...tive meu primeiro contato com a linguagem no ensino médio..."*
2. o trecho *"me introduziu a várias patterns, MVC, routes, e venho..."* também ficou meio confuso. Sugiro uma reescrita como *"me introduziu a vários patterns e conceitos como MVC e venho..."*

O restante ficou excelente!
