### ISSUE TITLE
Laravel Collections, uma solução?!

### ISSUE THREAD

**Issue by carusogabriel** [PHPSP/quero-palestrar#25]
Título: **Laravel Collections, uma solução?!**  
Palavras-chaves: `php`, `laravel`, `collections`, `higher-order functions`
Nível: *básico*  
Palestrante: [**Gabriel Caruso**](24)
Descrição da palestra:
> O objetivo desta palestra é mostrar uma carência do `PHP` no aninhamento de métodos, controle e poder de código com as [*higher-order functions*](https://www.wikiwand.com/en/Higher-order_function), refatoração e legibilidade de código com orientação a objetos (OOP) e como as [*collections*](https://laravel.com/docs/master/collections) do Laravel são poderosas para nos ajudar neste aspecto. 
É mostrado também como usar as *collections* fora do  [Laravel](https://laravel.com), e até em outras linguagens como o `JavaScript`.

Slides: https://speakerdeck.com/carusogabriel/collections-uma-solucao

**Comment by marcelgsantos** [comment]
Fala @gabriel-caruso, tudo bem?

Mais uma vez, ficou muito legal a proposta de sua palestra. Fiz alguns pequenos ajustes apenas para manter a consistência. :smiley: 

Sugiro apenas uma leve alteração no título da palestra de **Collections, uma solução?!** para **Laravel Collections, uma solução?!** para deixar claro sobre quais *collections* a sua palestra se refere *(importante para um evento que não é apenas sobre Laravel, por exemplo)*. 

Mas, como disse, é apenas uma sugestão e a decisão fica contigo.

Parabéns!

[]s
