### ISSUE TITLE
Are you testing the right things?

### ISSUE THREAD

**Issue by carusogabriel** [PHPSP/quero-palestrar#32]
Título: **Are you testing the right things?**
Palavras-chaves: `php`, `phpunit`, `testes`, `asserções`
Nível: *intermediário*
Palestrante: [**Gabriel Caruso**](24)
Descrição da palestra:
> Esta palestra é resultado de um projeto realizado por meses no `GitHub` e o ecossistema `PHP`.
O objetivo é a apresentação de métodos de asserção que o [`PHPUnit`](https://phpunit.de) possui que melhoram suíte de testes, inclusive no _debugging_ de erros. Não só métodos, mas também o caminho entre a asserção e a verificação, passagem de argumentos extras, mensagens de erro, etc.
A temática da palestra será a apresentação de blocos de asserções que são comuns, mostrando os benefícios da refatoração de código e melhoria de mensagens de erro.
Serão apresentadas diversas ferramentas para automatizar a refatoração destas asserções.

Slides: https://speakerdeck.com/carusogabriel/are-you-testing-the-right-things

**Comment by marcelgsantos** [comment]
Oi @carusogabriel, tudo bem?

Excelente proposta de palestra. Não vejo a hora de poder assistí-la em algum evento! ;)

**Sugestão:** eu tornaria a descrição da palestra **mais curta**. De 300 a 500 caracteres. Isso é importante pois **(1)** o público potencial de sua palestra pode optar por não ler a descrição por ela ser grande, logo você perde a chance de "vender" a sua palestra e, consequentemente, não gerar interesse no público. **(2)** Algumas ferramentas de call for papers pode não aceitar uma descrição tão grande quanto essa (com mais de 1.500 caracteres). **(3)** Não é uma tarefa fácil, mas tornar a descrição mais concisa trará vários benefícios.

**Comment by carusogabriel** [comment]
Muito obrigado pelo _feedback_ @marcelgsantos. Dei uma "refatorada" na descrição da palestra, mantendo os principais pontos:
- Projeto realizado no GitHub;
- Citação das asserções;
- Temática da palestra;
- Ferramentas para automatização destas refatorações;

Posso pedir uma _review_ antes de atualizar a descrição da _issue_?
> Esta palestra é resultado de um projeto realizado por meses no `GitHub` e o ecossistema `PHP`.
O objetivo é a apresentação de métodos de asserção que o [`PHPUnit`](https://phpunit.de) possui que melhoram suíte de testes, inclusive no _debugging_ de erros. Não só métodos, mas também o caminho entre a asserção e a verificação, passagem de argumentos extras, mensagens de erro, etc.
A temática da palestra será a apresentação de blocos de asserções que são comuns, mostrando os benefícios da refatoração de código e melhoria de mensagens de erro.
Serão apresentadas diversas ferramentas para automatizar a refatoração destas asserções.
